; resume.g
; called before a print from SD card is resumed
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Thu Feb 20 2020 13:55:54 GMT-0500 (Eastern Standard Time)

M98 P"0:sys/tunes/luckyTune.g" ; play tune
G1 R1 X0 Y0 Z5 F6000           ; go to 5mm above position of the last print move
G1 R1 X0 Y0                    ; go back to the last print move
M83                            ; relative extruder moves
G1 E10 F3600                   ; extrude 10mm of filament

