; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Thu Feb 20 2020 13:55:56 GMT-0500 (Eastern Standard Time)
; Wait for set temperatures to be reached
M116 P0

