; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2 on Mon Apr 01 2019 18:28:17 GMT-0400 (Eastern Daylight Time)

M561                ; clear any bed transform
M98 Presetprobe.g   ; reset BLtouch
M98 Pdeployprobe.g  ; deploy mechanical Z probe
G29                 ; probe the bed and enable compensation
M98 Pretractprobe.g ; retract mechanical Z probe


