; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v2 on Mon Apr 01 2019 18:28:19 GMT-0400 (Eastern Daylight Time)

M83                         ; relative extruder moves
G1 E-5 F3600                ; retract 5mm of filament
G91                         ; relative positioning
G1 Z150 X-300 Y300 F12000   ; move head from print
M106 P0 S0                  ; stop the fan

