; resetprobe.g
; resets a BLTouch alarm
;
; generated by RepRapFirmware Configuration Tool v2 on Mon Apr 01 2019 18:28:18 GMT-0400 (Eastern Daylight Time)

M280 P64 S160                                                        ; Alarm reset