; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v2 on Mon Apr 01 2019 18:28:18 GMT-0400 (Eastern Daylight Time)

M280 P64 S90                                      ; Retract BLTouch
