; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2 on Mon Apr 01 2019 18:28:20 GMT-0400 (Eastern Daylight Time)

