; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2 on Mon Apr 01 2019 18:28:21 GMT-0400 (Eastern Daylight Time)
; Wait for set temperatures to be reached


