; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Thu Feb 20 2020 13:55:52 GMT-0500 (Eastern Standard Time)

M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


