; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Thu Feb 20 2020 13:55:52 GMT-0500 (Eastern Standard Time)

M280 P0 S10             ; deploy Z probe

